name: when pull_request , auto build checking
on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # npmをキャッシュしてくれるやつ
      - name: yarn cache
        uses: bahmutov/npm-install@v1
      - name: can Build ? 🔧
        run: yarn build
